import { validatePresetCatalog } from './schema.js';
import { MODEL_VERSION } from '../core/model.js';
import type { PoliticalPreset, PoliticalActorType, PoliticalControlKey, PoliticalMapping } from './schema.js';
import { POLITICAL_CODING } from './coding-data.js';

const accessedAt='2026-10-05';
const logoMetadata:Record<string,{logo:{path:string;sourceUrl:string;sourceType:'OFFICIAL_WEBSITE'|'OFFICIAL_IDENTITY_GUIDE';retrievedAt:string};logoFallback:string;logoPresentation?:{scale?:number;maxWidth?:number;maxHeight?:number;objectPosition?:string}}>= {
  'preset-es-pp-23j-2023-v1':{logo:{path:'/assets/political-parties/pp.png',sourceUrl:'https://www.pp.es/wp-content/uploads/2024/12/logo-azul-e1734337769627.png',sourceType:'OFFICIAL_WEBSITE',retrievedAt:accessedAt},logoFallback:'PP'},
  'preset-es-psoe-23j-2023-v1':{logo:{path:'/assets/political-parties/psoe.png',sourceUrl:'https://www.psoe.es/media/themes/views/portadas/images/PSOE-footer.png',sourceType:'OFFICIAL_WEBSITE',retrievedAt:accessedAt},logoFallback:'PSOE'},
  'preset-es-vox-23j-2023-v1':{logo:{path:'/assets/political-parties/vox.svg',sourceUrl:'https://www.voxespana.es/wp-content/uploads/2023/07/Programa-VOX-2023-con-menos-peso.pdf',sourceType:'OFFICIAL_WEBSITE',retrievedAt:accessedAt},logoFallback:'VOX'},
  'preset-es-sumar-23j-2023-v1':{logo:{path:'/assets/political-parties/sumar.svg',sourceUrl:'https://movimientosumar.es/wp-content/uploads/2024/02/logo-00.svg',sourceType:'OFFICIAL_WEBSITE',retrievedAt:accessedAt},logoFallback:'SUMAR'},
  'preset-es-erc-23j-2023-v1':{logo:{path:'/assets/political-parties/erc.png',sourceUrl:'https://staticen.esquerra.cat/uploads/20200511/esquerra_erc_republicana_logotip.png',sourceType:'OFFICIAL_WEBSITE',retrievedAt:accessedAt},logoFallback:'ERC',logoPresentation:{scale:1.35}},
  'preset-es-pnv-23j-2023-v1':{logo:{path:'/assets/political-parties/eaj-pnv.png',sourceUrl:'https://www.eaj-pnv.eus/img/logotipo-eaj-pnv-2025-300.png',sourceType:'OFFICIAL_WEBSITE',retrievedAt:accessedAt},logoFallback:'EAJ-PNV'},
  'preset-es-bng-23j-2023-v1':{logo:{path:'/assets/political-parties/bng.svg',sourceUrl:'https://www.bng.gal/media/bnggaliza/files/2017/05/31/version_horizontal_logo_cor.zip',sourceType:'OFFICIAL_IDENTITY_GUIDE',retrievedAt:accessedAt},logoFallback:'BNG',logoPresentation:{scale:1.55}},
  'preset-es-upn-23j-2023-v1':{logo:{path:'/assets/political-parties/upn.png',sourceUrl:'https://www.upn.org/wp-content/uploads/2023/04/logo-200.png',sourceType:'OFFICIAL_WEBSITE',retrievedAt:accessedAt},logoFallback:'UPN'},
  'preset-es-junts-23j-2023-v1':{logo:{path:'/assets/political-parties/junts.svg',sourceUrl:'https://junts.cat/wp-content/uploads/2026/03/logo-junts.svg',sourceType:'OFFICIAL_WEBSITE',retrievedAt:accessedAt},logoFallback:'JUNTS'},
  'preset-es-eh-bildu-23j-2023-v1':{logo:{path:'/assets/political-parties/eh-bildu.png',sourceUrl:'https://ehbildu.eus/logo_eposta.png',sourceType:'OFFICIAL_WEBSITE',retrievedAt:accessedAt},logoFallback:'EH BILDU'},
  'preset-es-cc-23j-2023-v1':{logo:{path:'/assets/political-parties/coalicion-canaria.png',sourceUrl:'https://coalicioncanaria.org/wp-content/uploads/cc-pdf/documentos/Nueva%20Imagen%20de%20Coalici%C3%B3n%20Canaria.pdf',sourceType:'OFFICIAL_IDENTITY_GUIDE',retrievedAt:accessedAt},logoFallback:'CCa'},
};
const electionName='Elecciones Generales de España — 23J 2023';
const sources=[
  {id:'pp-23j',title:'Programa electoral 23J — Un proyecto al servicio de un gran país',url:'https://www.pp.es/storage/2023/07/programa_electoral_pp_23j_feijoo_2023.pdf',publisher:'Partido Popular',publishedAt:'2023-07-04',accessedAt},
  {id:'psoe-23j',title:'Programa electoral — Elecciones Generales 2023',url:'https://www.psoe.es/media-content/2023/07/PROGRAMA_ELECTORAL-GENERALES-2023.pdf',publisher:'Partido Socialista Obrero Español',publishedAt:'2023-07-07',accessedAt},
  {id:'vox-23j',title:'Programa electoral para las Elecciones Generales del 23J de 2023',url:'https://www.voxespana.es/wp-content/uploads/2023/07/Programa-VOX-2023-con-menos-peso.pdf',publisher:'VOX',publishedAt:null,accessedAt},
  {id:'sumar-23j',title:'Programa Electoral 23J',url:'https://movimientosumar.es/wp-content/uploads/2023/07/Un-Programa-para-ti.pdf',publisher:'Movimiento Sumar',publishedAt:null,accessedAt},
  {id:'erc-23j',title:'Programa Eleccions Generals 2023',url:'https://static.esquerra.cat/uploads/20230905/e2023-programa.pdf',publisher:'Esquerra Republicana de Catalunya',publishedAt:'2023-07-05',accessedAt},
  {id:'pnv-23j',title:'Con voz propia — Programa electoral 23-J',url:'https://www.eaj-pnv.eus/adjuntos/pnvDocumentos/20945_archivo.pdf',publisher:'EAJ-PNV',publishedAt:'2023-07-07',accessedAt},
  {id:'bng-23j',title:'Programa Electoral — Eleccións Xerais 2023',url:'https://www.bng.gal/media/bnggaliza/files/2023/07/05/23_bng_xerais_programa.pdf',publisher:'Bloque Nacionalista Galego',publishedAt:'2023-07-05',accessedAt},
  {id:'upn-23j',title:'Programa Electoral — Elecciones Generales 23 de julio 2023',url:'https://www.upn.org/wp-content/uploads/2023/07/Programa-Generales-23J_V2-1.pdf',publisher:'Unión del Pueblo Navarro',publishedAt:null,accessedAt},
  {id:'junts-23j',title:'Programa electoral 23J — Per Catalunya',url:'https://janhihaprou.cat/app/uploads/2023/07/Programa-Electoral.pdf',publisher:'Junts per Catalunya, Demòcrates de Catalunya y Més Esquerres de Catalunya',publishedAt:'2023-07-06',accessedAt},
  {id:'ehbildu-23j',title:'Compromiso de Euskal Herria Bildu · 23J',url:'https://ehbildu.eus/dokumentuak/23J-COMPROMISO-DE-EUSKAL-HERRIA-BILDU.pdf',publisher:'Euskal Herria Bildu',publishedAt:null,accessedAt},
  {id:'cc-23j',title:'Manifiesto: Un objetivo común, la defensa de Canarias',url:'https://coalicioncanaria.org/wp-content/uploads/2023/06/COALICION_POR_CANARIAS.pdf',publisher:'Coalición por Canarias',publishedAt:'2023-06-26',accessedAt},
];
const labels:Record<PoliticalControlKey,string>={taxShift:'Impuestos directos sobre hogares',progressivity:'Progresividad',consumptionTax:'Impuestos al consumo',corporateTax:'Impuesto de sociedades',transfers:'Transferencias monetarias',publicInvestment:'Inversión pública',services:'Gasto corriente en servicios públicos',investmentFriction:'Fricción a la inversión'};
const map=(sourceId:string,actorId:string,key:PoliticalControlKey,locator?:string):PoliticalMapping=>{const item=POLITICAL_CODING[actorId]?.[key];if(!item)throw new Error(`Falta codificación estandarizada: ${actorId} ${key}.`);const coded=item.score!==null,rationale=item.rationale,evidence=item.evidence,newActor=/preset-es-(junts|eh-bildu|cc)-/.test(actorId);return {status:coded?'APPROXIMATED':'UNMAPPED',value:null,unit:({taxShift:'pp',progressivity:'pp',consumptionTax:'%',corporateTax:'%',transfers:'%',publicInvestment:'% PIB',services:'% PIB',investmentFriction:'pp'} as const)[key],sourceIds:[sourceId],mappingMethod:coded?'STANDARDIZED_CODING':'NONE',positionScore:item.score,evidence,sourceSummary:rationale,sourceLocator:locator||(newActor?`Revisión temática del control ${key} en el documento programático oficial enlazado en el catálogo 23J.`:evidence.length?`Medidas ${evidence.join(', ')} en docs/political-presets/inventory/${actorId.replace('preset-es-','').replace('-23j-2023-v1','').replace('pnv','eaj-pnv')}-23j-2023.md.`:`Revisión de las medidas candidatas del control ${key}; ver docs/political-presets/inventory.`),sourceText:evidence.length?rationale:'No hay evidencia textual suficiente para fijar una posición.',mappingRationale:rationale,confidence:item.confidence,...(item.reviewStatus?{reviewStatus:item.reviewStatus}:{}),...(coded?{}:{unmappedReason:'INSUFFICIENT_TEXTUAL_EVIDENCE'})};};
const specs:Array<{id:string;actorName:string;actorType:PoliticalActorType;sourceId:string;description:string;seats:number;locators:Partial<Record<PoliticalControlKey,string>>}>=[
  {id:'preset-es-pp-23j-2023-v1',actorName:'Partido Popular (PP)',actorType:'PARTY',sourceId:'pp-23j',seats:137,description:'Programa oficial del Partido Popular para las elecciones generales del 23J de 2023.',locators:{taxShift:'Bloque “Crecer de forma sostenible” y propuestas de fiscalidad.',transfers:'Propuestas de servicios sociales y protección social.',publicInvestment:'Propuestas de inversión, infraestructuras y transición energética.',services:'Propuestas de servicios públicos y estado del bienestar.'}},
  {id:'preset-es-psoe-23j-2023-v1',actorName:'Partido Socialista Obrero Español (PSOE)',actorType:'PARTY',sourceId:'psoe-23j',seats:121,description:'Programa oficial del PSOE para las elecciones generales de julio de 2023.',locators:{taxShift:'Bloque I, “Una fiscalidad justa para un país moderno”.',progressivity:'Bloque I, “Una fiscalidad justa para un país moderno”.',transfers:'Bloques de políticas sociales y estado del bienestar.',publicInvestment:'Propuestas de inversión pública y transición ecológica.',services:'Estado del bienestar y provisión de servicios públicos.'}},
  {id:'preset-es-vox-23j-2023-v1',actorName:'VOX',actorType:'PARTY',sourceId:'vox-23j',seats:33,description:'Programa oficial de VOX para las elecciones generales del 23J de 2023.',locators:{taxShift:'Capítulo 9, “Fiscalidad para la prosperidad”.',progressivity:'Capítulo 9, “Fiscalidad para la prosperidad”.',consumptionTax:'Capítulo 9, “Fiscalidad para la prosperidad”.',corporateTax:'Capítulo 9, “Fiscalidad para la prosperidad”.',transfers:'Capítulo 8, “Protección social de los españoles”.',publicInvestment:'Capítulos económicos y de infraestructuras.',services:'Capítulos de salud, educación y protección social.'}},
  {id:'preset-es-sumar-23j-2023-v1',actorName:'Coalición Sumar',actorType:'COALITION',sourceId:'sumar-23j',seats:31,description:'Programa electoral oficial de la coalición Sumar para el 23J de 2023.',locators:{transfers:'Bloque VII, “Más igualdad y mejor protección social”; medidas 001–007 del inventario.',publicInvestment:'Propuestas de vivienda, I+D, PERTE y equipamientos en el inventario.',services:'Propuestas de cuidados, escuelas infantiles y servicios públicos.'}},
  {id:'preset-es-erc-23j-2023-v1',actorName:'Esquerra Republicana de Catalunya (ERC)',actorType:'PARTY',sourceId:'erc-23j',seats:7,description:'Programa oficial de ERC para las elecciones generales de 2023, orientado principalmente a Catalunya y los Països Catalans.',locators:{taxShift:'Economía, “Dèficit o prosperitat”; propuestas de ámbito estatal separadas de las territoriales.',transfers:'Derechos sociales y propuestas de ámbito estatal.',publicInvestment:'Infraestructuras, pp. 110–112; las medidas territoriales no se extrapolan.',services:'Sanidad y servicios sociales; ámbito territorial según cada medida.'}},
  {id:'preset-es-pnv-23j-2023-v1',actorName:'EAJ-PNV',actorType:'PARTY',sourceId:'pnv-23j',seats:5,description:'Programa oficial de EAJ-PNV “Con voz propia” para las elecciones generales del 23J de 2023, centrado en Euskadi.',locators:{taxShift:'Apartado 5, horizonte económico y fiscalidad justa; respeta regímenes forales.',progressivity:'Pág. impresa 15, adaptación del sistema tributario estatal con progresividad, equidad y justicia social.',transfers:'Apartados 9 y 12, pensiones y políticas sociales.',publicInvestment:'Págs. impresas 16–17, transición digital/ecológica, inversión pública y ejecución de fondos.',services:'Apartado 12, políticas sociales y estado del bienestar.'}},
  {id:'preset-es-bng-23j-2023-v1',actorName:'Bloque Nacionalista Galego (BNG)',actorType:'PARTY',sourceId:'bng-23j',seats:1,description:'Programa oficial del BNG para las elecciones generales de 2023, centrado en Galicia. Las medidas territoriales no se extrapolan.',locators:{taxShift:'Apartado 7.a, nueva fiscalidad; distinguir propuestas estatales y gallegas.',transfers:'Apartado 2, derechos sociales y prestaciones.',publicInvestment:'Apartado 9, infraestructuras; propuestas referidas a Galicia no se extrapolan.',services:'Apartado 6, servicios públicos de calidad.'}},
  {id:'preset-es-upn-23j-2023-v1',actorName:'Unión del Pueblo Navarro (UPN)',actorType:'PARTY',sourceId:'upn-23j',seats:1,description:'Programa oficial de UPN para las elecciones generales del 23 de julio de 2023, con medidas orientadas principalmente a Navarra.',locators:{taxShift:'Pág. impresa 2, objetivos de actuación en Cortes: reducir impuestos y deflactar la tarifa del IRPF.',transfers:'Pág. impresa 4, pensiones dignas y sin recortes; sin posición agregada clara sobre el conjunto de transferencias.',publicInvestment:'Apartados de infraestructuras y economía, con medidas territoriales navarras.',services:'Apartados de sanidad y educación referidos a Navarra.'}},
  {id:'preset-es-junts-23j-2023-v1',actorName:'Junts per Catalunya (Junts)',actorType:'COALITION',sourceId:'junts-23j',seats:7,description:'Programa oficial de la candidatura Junts per Catalunya para el 23J de 2023. Las propuestas catalanas no se extrapolan al conjunto estatal.',locators:{}},
  {id:'preset-es-eh-bildu-23j-2023-v1',actorName:'Euskal Herria Bildu (EH Bildu)',actorType:'COALITION',sourceId:'ehbildu-23j',seats:6,description:'Compromiso programático oficial de Euskal Herria Bildu para las elecciones generales del 23J de 2023.',locators:{progressivity:'Pág. PDF 8, compromisos fiscales sobre grandes fortunas, banca y energía.',transfers:'Págs. PDF 5 y 7, pensiones mínimas e ingreso mínimo vital.',publicInvestment:'Págs. PDF 6 y 8, infraestructuras e inversiones con componente territorial.',services:'Pág. PDF 6, refuerzo de Atención Primaria y salud mental, plazas PIR y cartera sanitaria pública.'}},
  {id:'preset-es-cc-23j-2023-v1',actorName:'Coalición Canaria (CCa)',actorType:'COALITION',sourceId:'cc-23j',seats:1,description:'Manifiesto oficial de Coalición por Canarias para las elecciones generales del 23J de 2023. Sus compromisos son territoriales y no se extrapolan.',locators:{}}
];
const raw:PoliticalPreset[]=specs.map(s=>{const presetSources=[sources.find(x=>x.id===s.sourceId)!];const policies=Object.fromEntries((Object.keys(labels) as PoliticalControlKey[]).map(key=>[key,map(s.sourceId,s.id,key,s.locators[key])])) as PoliticalPreset['policies'];
  return {id:s.id,country:'ES' as const,actorName:s.actorName,actorType:s.actorType,partyName:s.actorName,electionName,electionDate:'2023-07-23',version:'4.0.0',modelVersion:'0.3.0',cutoffDate:'2023-07-23',title:`Programa electoral · 23J 2023`,description:s.description,sources:presetSources,policies,doubleCountingCheck:'PASS' as const,congressSeats:s.seats,...logoMetadata[s.id]!};}).sort((a,b)=>b.congressSeats-a.congressSeats||a.actorName.localeCompare(b.actorName,'es'));

const validatedCatalog=validatePresetCatalog(raw);
export const POLITICAL_PRESET_BLOCKERS=validatedCatalog.filter(preset=>preset.modelVersion!==MODEL_VERSION).map(preset=>({actor:preset.actorName,reason:`El preset declara modelo ${preset.modelVersion}; el modelo activo es ${MODEL_VERSION}.`}));
if(POLITICAL_PRESET_BLOCKERS.length)console.warn('Se han excluido presets incompatibles del catálogo de producción.',POLITICAL_PRESET_BLOCKERS);
export const POLITICAL_PRESETS:PoliticalPreset[]=validatedCatalog.filter(preset=>preset.modelVersion===MODEL_VERSION);
export function findPoliticalPreset(id:string):PoliticalPreset|undefined {return POLITICAL_PRESETS.find(preset=>preset.id===id);}
