import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { once } from 'node:events';
import { createHash } from 'node:crypto';
import { cpSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { setTimeout as delay } from 'node:timers/promises';
import { replayRuntimeId } from '../scripts/replay-runtime.mjs';
import { archiveReplay } from '../scripts/replay-archive-lib.mjs';
import { selectBase, fingerprint } from '../dist/app/core/data.js';
import { createPrimaryExperiment, advance } from '../dist/app/core/engine.js';
import { baselinePolicy } from '../dist/app/core/policy.js';
import { MAX_SHARED_URL_LENGTH, scenarioUrl } from '../dist/app/ui/shared-scenario.js';

const original=JSON.parse(readFileSync('dist/build-info.json'));
const runtimeA=original.replayRuntimeId;
const archive=`dist/replay/${runtimeA}`;
assert.equal(JSON.parse(readFileSync(`${archive}/build-info.json`)).replayRuntimeId,runtimeA,'snapshot A registrado');
const assetsA=JSON.parse(readFileSync(`${archive}/asset-manifest.json`)).assets;
const videoA=assetsA['media/tutorial-simula-tu-pais.mp4'].path;
const posterA=assetsA['media/tutorial-simula-tu-pais-poster.webp'].path;
const logoA=assetsA['assets/political-parties/pp.png'].path;
const temporary=mkdtempSync(path.join(tmpdir(),'polis-replay-browser-'));
const buildB=path.join(temporary,'dist');cpSync('dist',buildB,{recursive:true});
const datasetPath=path.join(buildB,'data/spain.json'),datasetB=JSON.parse(readFileSync(datasetPath));
datasetB.version=`${datasetB.version}-upgrade-fixture`;
writeFileSync(datasetPath,JSON.stringify(datasetB));
const changedVideo=Buffer.from('vídeo distinto del runtime B');
const changedHash=createHash('sha256').update(changedVideo).digest('hex');
const changedVideoPath=`/replay/blobs/${changedHash}/asset.mp4`;
const changedVideoFile=path.join(buildB,changedVideoPath.slice(1));
import { mkdirSync } from 'node:fs';
mkdirSync(path.dirname(changedVideoFile),{recursive:true});
writeFileSync(changedVideoFile,changedVideo);
const rootAssets=JSON.parse(readFileSync(path.join(buildB,'asset-manifest.json')));
rootAssets.assets['media/tutorial-simula-tu-pais.mp4']={sha256:changedHash,path:changedVideoPath};
writeFileSync(path.join(buildB,'asset-manifest.json'),`${JSON.stringify(rootAssets,null,2)}\n`);
const runtimeB=replayRuntimeId(readFileSync(path.join(buildB,'app/worker.js')),readFileSync(datasetPath),readFileSync(path.join(buildB,'app/replay-kernel.js')));
assert.notEqual(runtimeB,runtimeA);
for(const name of ['app/main.js','app/replay-entry.js']){
  const file=path.join(buildB,name),contents=readFileSync(file,'utf8');
  assert.ok(contents.includes(runtimeA),`${name} incluye el runtime A`);
  writeFileSync(file,contents.replaceAll(runtimeA,runtimeB));
}
writeFileSync(path.join(buildB,'build-info.json'),JSON.stringify({...original,replayRuntimeId:runtimeB,
  hashes:{...original.hashes,'public/data/spain.json':createHash('sha256').update(readFileSync(datasetPath)).digest('hex')}}));
assert.equal(archiveReplay(buildB,path.join(buildB,'replay')).id,runtimeB);
const assetsB=JSON.parse(readFileSync(path.join(buildB,'replay',runtimeB,'asset-manifest.json'))).assets;
assert.notEqual(assetsB['media/tutorial-simula-tu-pais.mp4'].path,videoA,'B conserva otro vídeo');
assert.equal(assetsB['assets/political-parties/pp.png'].path,logoA,'A y B comparten el logo idéntico');
assert.equal(assetsB['media/tutorial-simula-tu-pais-poster.webp'].path,posterA,'A y B comparten el poster idéntico');
const server=spawn(process.execPath,[path.resolve('scripts/serve.mjs')],{cwd:temporary,env:{...process.env,PORT:'0',HOST:'127.0.0.1'},stdio:['ignore','pipe','pipe']});
let browser,ws;
async function waitFor(fn,label){const end=Date.now()+20000;while(Date.now()<end){const result=await fn();if(result)return result;await delay(80);}throw new Error(`Tiempo agotado: ${label}`);}
try{
  const baseUrl=await new Promise((resolve,reject)=>{let output='';server.stdout.on('data',chunk=>{output+=chunk;const match=output.match(/http:\/\/127\.0\.0\.1:\d+/);if(match)resolve(match[0]);});server.on('error',reject);});
  for(const name of ['index.html','style.css','theme.js','asset-manifest.json','app/main.js','app/worker.js','app/replay-entry.js','data/spain.json','licenses/fflate-LICENSE']){
    assert.equal((await fetch(`${baseUrl}/replay/${runtimeA}/${name}`,{method:'HEAD'})).status,200,`${name} autocontenido`);
  }
  for(const asset of Object.values(assetsA))assert.equal((await fetch(`${baseUrl}${asset.path}`,{method:'HEAD'})).status,200,`${asset.path} publicado`);
  assert.equal((await fetch(`${baseUrl}/replay/${runtimeA}/media/tutorial-simula-tu-pais.mp4`,{method:'HEAD'})).status,404,'sin vídeo duplicado en A');
  assert.equal((await fetch(`${baseUrl}/replay/${runtimeA}/assets/political-parties/pp.png`,{method:'HEAD'})).status,404,'sin logo duplicado en A');
  assert.equal((await fetch(`${baseUrl}/replay/${runtimeA}/replay/runtime-manifest.json`)).status,404,'sin archivo de runtimes recursivo');
  assert.equal((await fetch(`${baseUrl}/media/tutorial-simula-tu-pais.mp4`,{method:'HEAD'})).status,404,'root B no duplica el vídeo');
  const datasetA=JSON.parse(readFileSync(`${archive}/data/spain.json`));
  const base=selectBase(datasetA),policy={...baselinePolicy(base),taxShift:2,transfers:10,publicInvestment:3.3};
  const exp=advance(createPrimaryExperiment(base,1847,policy,true),36);
  const publicUrl=scenarioUrl(exp,fingerprint(JSON.stringify(datasetA)),datasetA.countryCode,'B',baseUrl,runtimeA);
  const snapshotUrl=new URL(publicUrl);snapshotUrl.pathname=`/replay/${runtimeA}/`;
  const port=12000+(process.pid%1000);
  browser=spawn(process.env.CHROMIUM||'/usr/bin/google-chrome',['--headless=new','--no-sandbox','--disable-gpu','--disable-dev-shm-usage',`--remote-debugging-port=${port}`,`--user-data-dir=${path.join(temporary,'profile')}`,'about:blank'],{stdio:'ignore'});
  const target=await waitFor(async()=>{try{return (await (await fetch(`http://127.0.0.1:${port}/json/list`)).json()).find(item=>item.type==='page');}catch{return null;}},'Chromium');
  ws=new WebSocket(target.webSocketDebuggerUrl);await once(ws,'open');
  let callId=0;const pending=new Map(),errors=[],requests=[];
  ws.addEventListener('message',event=>{const message=JSON.parse(event.data);if(message.method==='Runtime.exceptionThrown')errors.push(message.params.exceptionDetails?.text||'Error de página');if(message.method==='Network.requestWillBeSent')requests.push(message.params.request.url);if(message.id&&pending.has(message.id)){const p=pending.get(message.id);pending.delete(message.id);message.error?p.reject(new Error(message.error.message)):p.resolve(message.result);}});
  const cdp=(method,params={})=>new Promise((resolve,reject)=>{const id=++callId;pending.set(id,{resolve,reject});ws.send(JSON.stringify({id,method,params}));});
  const evaluate=async expression=>{const result=await cdp('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(result.exceptionDetails)throw new Error(result.exceptionDetails.text);return result.result?.value;};
  const navigate=url=>cdp('Page.navigate',{url});
  const click=selector=>evaluate(`document.querySelector(${JSON.stringify(selector)})?.click()`);
  const kpis=()=>evaluate(`JSON.stringify([...document.querySelectorAll('.kpi-main')].map(item=>item.textContent))`);
  await cdp('Page.enable');await cdp('Runtime.enable');await cdp('Network.enable');
  await navigate(`${baseUrl}/replay/${runtimeB}/`);
  await waitFor(async()=>evaluate(`!!document.querySelector('[data-action="open-tutorial"]')`),'snapshot B con otro vídeo');
  await click('[data-action="open-tutorial"]');
  await waitFor(async()=>evaluate(`!!document.querySelector('#tutorial-video source')`),'tutorial de B');
  assert.equal(await evaluate(`document.querySelector('#tutorial-video source')?.getAttribute('src')`),assetsB['media/tutorial-simula-tu-pais.mp4'].path,'B carga su propio vídeo');
  await click('[data-action="close-tutorial"]');
  await navigate(`${baseUrl}/`);
  await waitFor(async()=>evaluate(`!!document.querySelector('[data-action="open-tutorial"]')`),'root B disponible');
  await click('[data-action="open-tutorial"]');
  await waitFor(async()=>evaluate(`!!document.querySelector('#tutorial-video source')`),'tutorial del root B');
  assert.equal(await evaluate(`document.querySelector('#tutorial-video source')?.getAttribute('src')`),changedVideoPath,'root B usa el blob Y');
  assert.equal(await evaluate(`(async()=>{const res=await fetch(${JSON.stringify(changedVideoPath)},{method:'HEAD'});return res.status})()`),200);
  assert.ok(requests.some(url=>url===`${baseUrl}${changedVideoPath}`),'Network registra el blob Y desde root B');
  await click('[data-action="close-tutorial"]');
  await navigate(snapshotUrl.href);
  await waitFor(async()=>evaluate(`document.querySelectorAll('.kpi-main').length===6`),'resultado original de A');
  const originalKpis=await kpis();
  assert.equal(await evaluate(`location.pathname`),`/replay/${runtimeA}/`);
  assert.equal(await evaluate(`document.querySelector('.tutorial-thumbnail img')?.getAttribute('src')`),posterA,'poster inmutable de A');
  await click('[data-action="open-tutorial"]');
  await waitFor(async()=>evaluate(`!!document.querySelector('#tutorial-video source')`),'vídeo histórico');
  assert.equal(await evaluate(`document.querySelector('#tutorial-video source')?.getAttribute('src')`),videoA,'A usa su vídeo content-addressed');
  assert.equal(await evaluate(`document.querySelector('#tutorial-video')?.getAttribute('poster')`),posterA);
  assert.equal(await evaluate(`(async()=>{const res=await fetch(${JSON.stringify(videoA)},{method:'HEAD'});return res.status+' '+res.headers.get('content-type');})()`),'200 video/mp4');
  assert.equal(await evaluate(`(async()=>{const res=await fetch(${JSON.stringify(logoA)});return res.status+' '+res.headers.get('content-type');})()`),'200 image/png');
  assert.ok(requests.some(url=>url===`${baseUrl}${videoA}`),'Network registra el blob de vídeo de A');
  assert.ok(requests.some(url=>url===`${baseUrl}${logoA}`),'Network registra el blob del logo de A');
  assert.ok(!requests.some(url=>url===`${baseUrl}/media/tutorial-simula-tu-pais.mp4`),'A no solicita el vídeo mutable de B');
  await click('[data-action="close-tutorial"]');
  const requestStart=requests.length;
  await navigate(publicUrl);
  await waitFor(async()=>evaluate(`location.pathname===${JSON.stringify(`/replay/${runtimeA}/`)}&&document.querySelectorAll('.kpi-main').length===6`),'redirección B a A');
  assert.equal(await kpis(),originalKpis,'KPI numéricos idénticos tras upgrade B → replay A');
  assert.ok(!requests.slice(requestStart).some(url=>url===`${baseUrl}/data/spain.json`),'root B no carga su dataset antes de redirigir');
  const nearLimit=new URL(publicUrl);nearLimit.searchParams.set('pad','');
  const fill=MAX_SHARED_URL_LENGTH-nearLimit.href.length;nearLimit.searchParams.set('pad','x'.repeat(fill));
  assert.equal(nearLimit.href.length,MAX_SHARED_URL_LENGTH);
  await navigate(nearLimit.href);
  await waitFor(async()=>evaluate(`location.pathname===${JSON.stringify(`/replay/${runtimeA}/`)}&&document.querySelectorAll('.kpi-main').length===6`),'URL límite redirigida');
  assert.ok(await evaluate(`location.href.length>${MAX_SHARED_URL_LENGTH}`),'la ruta interna supera el límite público');
  assert.equal(await kpis(),originalKpis,'se acepta el límite canónico dentro de replay');
  await click('[data-action="decisions-toggle"]');
  await waitFor(async()=>evaluate(`!!document.querySelector('[data-policy="services"]')`),'configuración histórica');
  await evaluate(`(()=>{const input=document.querySelector('[data-policy="services"]');input.value='19.4';input.dispatchEvent(new Event('input',{bubbles:true}));input.dispatchEvent(new Event('change',{bubbles:true}));})()`);
  await click('[data-action="apply-decisions"]');
  await waitFor(async()=>evaluate(`!!document.querySelector('[data-action="confirm-dialog"]')`),'confirmación de comparación');
  await click('[data-action="confirm-dialog"]');
  await waitFor(async()=>evaluate(`!!document.querySelector('#observed-branch')`),'variante histórica');
  const beforeDate=await evaluate(`document.querySelector('#sim-date')?.textContent`);
  await click('[data-action="step"]');
  await waitFor(async()=>evaluate(`document.querySelector('#sim-date')?.textContent!==${JSON.stringify(beforeDate)}`),'avance de variante');
  await click('[data-action="share-options"]');
  const variant=await evaluate(`document.querySelector('#share-url-manual')?.value`);
  assert.notEqual(variant,publicUrl);
  assert.equal(new URL(variant).pathname,'/','enlace canónico desde snapshot');
  assert.equal(new URL(variant).searchParams.get('r'),runtimeA,'la variante sigue perteneciendo a A');
  assert.equal(new URL(variant).searchParams.get('v'),'2');
  assert.equal(new URL(variant).searchParams.get('c'),'d');
  const tooLong=new URL(nearLimit);tooLong.searchParams.set('pad','x'.repeat(fill+1));
  await navigate(tooLong.href);
  await waitFor(async()=>evaluate(`document.querySelector('#toast')?.textContent.includes('No se pudo abrir el escenario')`),'URL pública superior al límite');
  assert.ok((await evaluate(`document.querySelector('#toast')?.textContent`)).includes('demasiados cambios'));
  const unknown=new URL(publicUrl);unknown.searchParams.set('r',`rt-${'f'.repeat(32)}`);
  await navigate(unknown.href);
  await waitFor(async()=>evaluate(`document.querySelector('.boot h1')?.textContent==='No se pudo abrir el escenario'`),'runtime desconocido');
  assert.equal(await evaluate(`document.querySelector('.boot p')?.textContent`),'Este escenario fue creado con una versión del simulador que no está disponible.');
  assert.equal(await evaluate(`document.querySelector('.boot a')?.getAttribute('href')`),'/');
  assert.equal(await evaluate(`!!document.querySelector('.kpi-main')`),false,'no se ejecuta la receta con B');
  const noCodec=new URL(publicUrl);noCodec.searchParams.delete('c');
  await navigate(noCodec.href);
  await waitFor(async()=>evaluate(`document.querySelector('.boot h1')?.textContent==='No se pudo abrir el escenario'`),'codec ausente');
  assert.equal(await evaluate(`!!document.querySelector('.kpi-main')`),false);
  const traversal=new URL(publicUrl);traversal.searchParams.set('r','../externo');
  await navigate(traversal.href);
  await waitFor(async()=>evaluate(`document.querySelector('.boot h1')?.textContent==='No se pudo abrir el escenario'`),'runtime ID inseguro');
  assert.equal(await evaluate(`location.pathname`),'/','un ID no puede construir otra ruta');
  assert.equal(await evaluate(`!!document.querySelector('.kpi-main')`),false);
  assert.deepEqual(errors,[]);
  console.log(`PASS replay E2E: A ${runtimeA} → B ${runtimeB} → snapshot A; KPI exactos, blobs de A en Network, límite canónico 8192, variante canónica y entradas inválidas rechazadas.`);
}finally{
  ws?.close();
  if(browser?.exitCode===null){const exited=once(browser,'exit');browser.kill();await exited;}
  if(server.exitCode===null){const exited=once(server,'exit');server.kill();await exited;}
  rmSync(temporary,{recursive:true,force:true});
}
