import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { performance } from 'node:perf_hooks';
import { selectBase, fingerprint, REQUIRED } from '../dist/app/core/data.js';
import { createExperiment, advance, fork, householdBudget, initialState, validateState } from '../dist/app/core/engine.js';
import { baselinePolicy, validatePolicy, economicProximity, BOUNDS } from '../dist/app/core/policy.js';
import { exportSession, validateSession, restoreSession } from '../dist/app/core/session.js';
import { draw, externalAt } from '../dist/app/core/random.js';
import { M, MODEL_VERSION, MAX_MONTHS } from '../dist/app/core/model.js';
import { esc, dateLabel } from '../dist/app/ui/format.js';
const data=JSON.parse(readFileSync(new URL('../public/data/spain.json',import.meta.url)));
const base=selectBase(data), policy=baselinePolicy(base), hash=fingerprint(JSON.stringify(data));
const fresh=(p=policy,seed=123)=>createExperiment(base,seed,p);
const near=(a,b,tol=1e-8)=>assert.ok(Math.abs(a-b)<=tol*Math.max(1,Math.abs(a)),`${a} != ${b}`);
const copy=()=>structuredClone(data);
test('el ano se obtiene del catalogo, no del reloj',()=>assert.equal(base.year,Math.max(...data.observations.map(o=>o.baseYear))));
test('cobertura completa y origen de las variables',()=>{assert.equal(base.observations.length,REQUIRED.length);for(const o of base.observations){assert.match(o.source,/^https:\/\//);assert.ok(o.referencePeriod&&o.published&&o.unit);}});
test('un ejercicio nuevo completo cambia automaticamente la base',()=>{const d=copy();d.observations.push(...base.observations.map(o=>({...o,baseYear:2031})));assert.equal(selectBase(d).year,2031);});
test('un dato mas reciente aislado no desplaza la base',()=>{const d=copy();d.observations.push({...base.observations[0],baseYear:2032});assert.equal(selectBase(d).year,base.year);});
test('las proyecciones no desplazan la base',()=>{const d=copy();d.observations.push(...base.observations.map(o=>({...o,baseYear:2032,kind:'projection'})));assert.equal(selectBase(d).year,base.year);});
test('una carencia esencial hace retroceder al ejercicio completo previo',()=>{const d=copy();d.observations=d.observations.filter(o=>!(o.id==='debt'&&o.baseYear===base.year));assert.equal(selectBase(d).year,base.year-1);});
test('se rechaza un catalogo sin cobertura',()=>assert.throws(()=>selectBase({...data,observations:[]})));
test('se rechaza una identidad de PIB incoherente',()=>{const d=copy();d.observations.find(o=>o.id==='gdp'&&o.baseYear===base.year).value+=100;assert.throws(()=>selectBase(d),/concilian/);});
test('la seleccion utiliza la revision mas reciente de una serie',()=>{const d=copy();d.observations.push({...base.observations.find(o=>o.id==='debt'),value:1700,published:'2030-01-01'});assert.equal(selectBase(d).values.debt,1700);});
test('identidades del estado inicial',()=>validateState(initialState(base)));
test('las ramas parten de exactamente la misma situacion heredada',()=>{const e=fresh({...policy,taxShift:4});assert.deepEqual(e.a.state,e.b.state);});
test('parametros iguales producen cifras exactamente iguales',()=>{const e=advance(fresh(),120);assert.deepEqual(e.a.state,e.b.state);assert.deepEqual(e.a.history,e.b.history);});
test('avanzar 120 meses juntos o de uno en uno no altera nada',()=>{const one=advance(fresh({...policy,taxShift:3}),120);let many=fresh({...policy,taxShift:3});for(let i=0;i<120;i++)many=advance(many,1);assert.deepEqual(one,many);});
test('reproducibilidad entre ejecuciones',()=>assert.deepEqual(advance(fresh(),60),advance(fresh(),60)));
test('el RNG acepta semilla cero y es reproducible',()=>{assert.equal(draw(0,5,2),draw(0,5,2));assert.notEqual(draw(0,5,2),draw(1,5,2));assert.equal(fresh(policy,0).seed,0);});
test('los choques externos no dependen de la rama ni del orden de llamadas',()=>{const a=externalAt(45,10);for(let i=0;i<100;i++)draw(45,i,20);assert.deepEqual(a,externalAt(45,10));});
test('canales aleatorios independientes',()=>assert.notEqual(draw(12,12,1),draw(12,12,2)));
test('semillas distintas generan trayectorias distintas',()=>assert.notDeepEqual(advance(fresh(policy,1),120).a.history,advance(fresh(policy,2),120).a.history));
test('el impuesto directo reduce la renta exactamente a ingresos constantes',()=>{const a=householdBudget(1000,50000000,1,policy),b=householdBudget(1000,50000000,1,{...policy,taxShift:4});a.forEach((h,i)=>near(h.disposable-b[i].disposable,h.gross*.04));});
test('transferencias aumentan renta directamente con contrapartida',()=>{const a=householdBudget(1000,50000000,1,policy),b=householdBudget(1000,50000000,1,{...policy,transfers:10});a.forEach((h,i)=>near(b[i].disposable-h.disposable,h.transfers*.1));});
test('progresividad produce efectos distintos por grupo',()=>{const a=householdBudget(1000,50000000,1,policy),b=householdBudget(1000,50000000,1,{...policy,progressivity:4});assert.ok(b[0].disposable>a[0].disposable);assert.ok(b[2].disposable<a[2].disposable);near(b[1].disposable,a[1].disposable);});
test('doblar precios reduce a la mitad renta real a renta nominal fija',()=>{const a=householdBudget(1000,50000000,1,policy),b=householdBudget(1000,50000000,2,policy);a.forEach((h,i)=>near(h.realPerPerson/2,b[i].realPerPerson));});
test('mas friccion disminuye la inversion deseada por su mecanismo declarado',()=>{const e=advance(fresh({...policy,investmentFriction:4}),1);assert.ok(e.b.state.trace.find(t=>t.id==='investment').result<e.a.state.trace.find(t=>t.id==='investment').result);});
test('impuesto al consumo aplica factor de nivel sin capitalizarlo cada mes',()=>{const e=advance(fresh({...policy,consumptionTax:16}),24);near(e.b.state.consumerPrice/e.b.state.producerPrice,1.16/1.11);});
test('renta, capital, deuda y demanda concilian cada mes',()=>{let e=fresh({...policy,taxShift:4,transfers:15,publicInvestment:5});for(let i=0;i<240;i++){const old=e;e=advance(e,1);validateState(e.a.state,old.a.state);validateState(e.b.state,old.b.state);near(e.b.state.capital,old.b.state.capital*(1-M.depreciation/12)+e.b.state.investment/12);}});
test('las funciones no mutan la entrada',()=>{const e=fresh();const prior=structuredClone(e);advance(e,12);assert.deepEqual(e,prior);});
test('bifurcar conserva capital, deuda, poblacion e historia de A',()=>{const e=advance(fresh({...policy,taxShift:3}),12),f=fork(e,{...policy,taxShift:-3});assert.deepEqual(f.a,e.a);assert.deepEqual(f.b.state,e.a.state);assert.deepEqual(f.b.history,e.a.history);assert.equal(f.forkMonth,12);});
test('exportacion y restauracion despues de una bifurcacion',()=>{const e=advance(fork(advance(fresh(),24),{...policy,taxShift:5,transfers:10}),36);const s=validateSession(JSON.parse(JSON.stringify(exportSession(e,hash))),base,hash);assert.deepEqual(restoreSession(s,base),e);});
test('restaurar un escenario bifurcado en mes cero es exacto',()=>{const e=advance(fresh({...policy,taxShift:2}),12);const r=restoreSession(exportSession(e,hash),base);assert.deepEqual(r,e);});
test('no se reinterpretan versiones de datos o de motor',()=>{const s=exportSession(fresh(),hash);assert.throws(()=>validateSession({...s,modelVersion:'999'},base,hash));assert.throws(()=>validateSession({...s,datasetVersion:'otro'},base,hash));assert.throws(()=>validateSession({...s,datasetHash:'otro'},base,hash));});
test('importacion rechaza NaN, horizonte abusivo, bifurcacion imposible y seed invalida',()=>{const s=exportSession(fresh(),hash);for(const patch of [{seed:-1},{months:MAX_MONTHS+1},{months:1,forkMonth:2},{seed:1.1}])assert.throws(()=>validateSession({...s,...patch},base,hash));assert.throws(()=>validatePolicy({...policy,taxShift:NaN}));});
test('importacion no ejecuta ni preserva campos arbitrarios',()=>{const s=exportSession(fresh(),hash);const safe=validateSession({...s,html:'<script>bad</script>',branches:{...s.branches,B:{...s.branches.B,initialPolicy:{...s.branches.B.initialPolicy,eval:'bad',equation:'bad'}}}},base,hash);assert.equal(safe.html,undefined);assert.equal(safe.branches.B.initialPolicy.eval,undefined);assert.equal(safe.branches.B.initialPolicy.equation,undefined);});
test('escapado HTML de todos los metadatos renderizables',()=>assert.equal(esc('<img src=x onerror="bad">'), '&lt;img src=x onerror=&quot;bad&quot;&gt;'));
test('los parametros institucionales no ocultan penalizaciones economicas',()=>{const e=advance(fresh({...policy,elections:'single-party',expression:false,judicialReview:false}),120);assert.deepEqual(e.a.state,e.b.state);});
test('los procesos institucionales generan eventos, nunca ganadores',()=>{const e=advance(fresh({...policy,elections:'single-party',termMonths:24}),48);assert.equal(e.b.events.filter(e=>e.type==='institution').length,2);assert.equal(e.a.events.filter(e=>e.type==='institution').length,1);});
test('la clasificacion descriptiva no modifica los parametros ni la simulacion',()=>{const p={...policy,taxShift:4};const before=structuredClone(p);economicProximity(p);assert.deepEqual(p,before);assert.deepEqual(advance(fresh(p),12),advance(fresh(before),12));});
test('los porcentajes descriptivos estan acotados y son independientes',()=>{const r=economicProximity(policy);r.values.forEach(v=>assert.ok(v>=0&&v<=100));assert.notEqual(r.values.reduce((a,b)=>a+b,0),100);});
test('la historia usa meses sin desfases de zona horaria',()=>{assert.equal(dateLabel(2030,0),'Cierre 2030');assert.match(dateLabel(2030,1),/2031/);assert.match(dateLabel(2030,12),/2031/);assert.match(dateLabel(2030,13),/2032/);});
test('el horizonte se acota sin avanzar mas alla',()=>{const e=advance(fresh(),MAX_MONTHS);assert.equal(advance(e,12).a.state.month,MAX_MONTHS);assert.throws(()=>advance(fresh(),0));assert.throws(()=>advance(fresh(),.5));});
test('matriz de extremos y semillas conserva valores finitos',()=>{
 for(let seed=0;seed<20;seed++){
  const p={...policy};for(const [k,[min,max]] of Object.entries(BOUNDS)){if(k!=='termMonths')p[k]=seed%2?min:max;}
  const e=advance(fresh(p,seed),240);validateState(e.b.state);assert.equal(e.b.history.length,241);
 }
});
test('cada cambio tiene mecanismos registrados con entradas finitas',()=>{const e=advance(fresh(),1);assert.equal(e.b.state.trace.length,8);for(const t of e.b.state.trace){assert.ok(t.equation&&t.explanation);assert.ok(Number.isFinite(t.result));Object.values(t.inputs).forEach(v=>assert.ok(Number.isFinite(v)));}});
test('modelo exportado contiene version explicita',()=>assert.equal(exportSession(fresh(),hash).modelVersion,MODEL_VERSION));
test('benchmark orientativo de una comparacion a 20 anos',t=>{const start=performance.now();advance(fresh({...policy,investmentFriction:2}),240);t.diagnostic(`240 meses, dos ramas: ${(performance.now()-start).toFixed(1)} ms en este entorno (no garantiza rendimiento movil).`);});
