// Every behavioral coefficient below is an explicit hypothesis, not an empirical estimate.
export const MODEL_VERSION = '0.3.0';
export const MAX_MONTHS = 240;
export const M = Object.freeze({
  grossIncomeShare: 0.66, transferGDPShare: 0.17,
  populationShares: [0.4, 0.4, 0.2] as readonly number[],
  incomeShares: [0.18, 0.4, 0.42] as readonly number[],
  transferShares: [0.55, 0.35, 0.1] as readonly number[],
  effectiveIncomeTaxes: [0.08, 0.18, 0.28] as readonly number[],
  consumptionPropensity: [0.94, 0.83, 0.62] as readonly number[],
  baselineConsumptionTax: 0.11, baselineCorporateTax: 0.2,
  baselinePublicInvestment: 0.03, corporateProfitShare: 0.25,
  socialContributionShare: 0.1, otherRevenueShare: 0.045,
  productivityGrowth: 0.003, capitalOutputRatio: 3.2, depreciation: 0.04,
  capitalElasticity: 0.27, investmentReturnElasticity: 1.25, frictionElasticity: 3,
  outputAdjustment: 0.32, capacityHeadroom: 0.05, inflationAnchor: 0.02,
  inflationPersistence: 0.97, gapPriceResponse: 0.10, consumptionTaxPassThrough: 0.50,
  energyPriceExposure: 0.16, externalDemandExposure: 0.35,
  okunCoefficient: 0.22, debtInterest: 0.025,
  externalDemandGrowth: 0.02, importDemandElasticity: 1, eventMonthlyChance: 0.10,
  minInflation: -0.04, maxInflation: 0.30, minUnemployment: 0.015, maxUnemployment: 0.45,
});
const PARAMETER_META:Record<string,{name:string;unit:string;category:'OBSERVADO'|'DERIVADO'|'HEURISTICO'|'LITERATURA';description:string;reference:string}>={
  grossIncomeShare:{name:'Proporción de renta bruta de hogares',unit:'proporción del PIB',category:'HEURISTICO',description:'Participación sintética.',reference:'docs/model-validation/model-parameters.md'},
  transferGDPShare:{name:'Transferencias a hogares',unit:'proporción del PIB',category:'HEURISTICO',description:'Importe y reparto sintéticos; no equivale al total observado de prestaciones.',reference:'docs/model-validation/phase2/C-households-fiscal.md'},
  populationShares:{name:'Cuotas de población por grupo',unit:'proporción',category:'HEURISTICO',description:'Tres grupos estilizados, no cuantiles observados.',reference:'docs/model-validation/phase2/C-households-fiscal.md'},
  incomeShares:{name:'Cuotas de renta por grupo',unit:'proporción',category:'HEURISTICO',description:'Distribución sintética.',reference:'docs/model-validation/phase2/C-households-fiscal.md'},
  transferShares:{name:'Cuotas de transferencias',unit:'proporción',category:'HEURISTICO',description:'Reparto sintético entre grupos.',reference:'docs/model-validation/phase2/C-households-fiscal.md'},
  effectiveIncomeTaxes:{name:'Tipos efectivos estilizados',unit:'proporción',category:'HEURISTICO',description:'No son tipos IRPF observados.',reference:'docs/model-validation/phase2/C-households-fiscal.md'},
  consumptionPropensity:{name:'Propensiones al consumo',unit:'proporción',category:'HEURISTICO',description:'Regla de comportamiento por grupo.',reference:'docs/model-validation/phase2/C-households-fiscal.md'},
  baselineConsumptionTax:{name:'Referencia del impuesto al consumo',unit:'proporción',category:'HEURISTICO',description:'Tipo medio sintético.',reference:'docs/model-validation/model-equations.md'},
  baselineCorporateTax:{name:'Referencia del impuesto de sociedades',unit:'proporción',category:'HEURISTICO',description:'Tipo de referencia para la regla de inversión.',reference:'docs/model-validation/model-equations.md'},
  baselinePublicInvestment:{name:'Referencia de inversión pública',unit:'proporción del PIB',category:'HEURISTICO',description:'Referencia de escenario.',reference:'docs/model-validation/model-equations.md'},
  corporateProfitShare:{name:'Base sintética de beneficios',unit:'proporción del PIB',category:'HEURISTICO',description:'No es una base observada de cuentas nacionales.',reference:'docs/model-validation/phase2/C-households-fiscal.md'},
  socialContributionShare:{name:'Cotizaciones sintéticas',unit:'proporción del PIB',category:'HEURISTICO',description:'Cuota de ingreso público simplificada.',reference:'docs/model-validation/phase2/C-households-fiscal.md'},
  otherRevenueShare:{name:'Otros ingresos sintéticos',unit:'proporción del PIB',category:'HEURISTICO',description:'Cuota agregada simplificada.',reference:'docs/model-validation/phase2/C-households-fiscal.md'},
  productivityGrowth:{name:'Productividad tendencial',unit:'por año',category:'LITERATURA',description:'Candidato provisional del BdE; no es estimación estructural propia ni crecimiento potencial total.',reference:'docs/model-validation/phase2/A-production-investment.md'},
  capitalOutputRatio:{name:'Capital inicial / producto',unit:'años',category:'HEURISTICO',description:'Existencia inicial construida mediante una razón supuesta.',reference:'docs/model-validation/phase2/A-production-investment.md'},
  depreciation:{name:'Depreciación agregada',unit:'por año',category:'HEURISTICO',description:'Tasa homogénea para un stock agregado.',reference:'docs/model-validation/phase2/A-production-investment.md'},
  capitalElasticity:{name:'Contribución del crecimiento neto del capital a capacidad',unit:'adimensional',category:'HEURISTICO',description:'Coeficiente conservado de 0.2.0 aplicado al crecimiento neto del stock; no es una elasticidad estimada para España.',reference:'docs/model-validation/model-0.3.0-parameters.md'},
  investmentReturnElasticity:{name:'Respuesta de inversión a rentabilidad',unit:'adimensional',category:'HEURISTICO',description:'Exponente fiscal conservado.',reference:'docs/model-validation/phase2/A-production-investment.md'},
  frictionElasticity:{name:'Respuesta a fricción de inversión',unit:'adimensional',category:'HEURISTICO',description:'Exponente conservado en la función exponencial.',reference:'docs/model-validation/phase2/A-production-investment.md'},
  outputAdjustment:{name:'Ajuste de producción',unit:'por mes',category:'HEURISTICO',description:'Velocidad de ajuste reducida.',reference:'docs/model-validation/phase2/A-production-investment.md'},
  capacityHeadroom:{name:'Margen transitorio de utilización',unit:'proporción',category:'HEURISTICO',description:'Margen de utilización transitoria del modelo; no estima capacidad ociosa española.',reference:'docs/model-validation/model-0.3.0-parameters.md'},
  inflationAnchor:{name:'Ancla de inflación',unit:'por año',category:'LITERATURA',description:'Ancla nominal del 2 %; no es previsión.',reference:'docs/model-validation/phase2-B-employment-inflation.md'},
  inflationPersistence:{name:'Persistencia de inflación',unit:'por mes',category:'HEURISTICO',description:'Elección provisional para memoria de varios trimestres.',reference:'docs/model-validation/phase2-B-employment-inflation.md'},
  gapPriceResponse:{name:'Respuesta de precios a la brecha',unit:'adimensional',category:'HEURISTICO',description:'Proxy de holgura; no coeficiente causal estimado.',reference:'docs/model-validation/phase2-B-employment-inflation.md'},
  consumptionTaxPassThrough:{name:'Traslado del impuesto al consumo',unit:'fracción del cambio mecánico',category:'HEURISTICO',description:'Traslado central simplificado, una sola vez al nivel de precios.',reference:'docs/model-validation/phase2-B-employment-inflation.md'},
  energyPriceExposure:{name:'Exposición a energía',unit:'adimensional',category:'HEURISTICO',description:'Exposición sintética ante perturbaciones externas.',reference:'docs/model-validation/phase2-B-employment-inflation.md'},
  externalDemandExposure:{name:'Exposición a demanda exterior',unit:'adimensional',category:'HEURISTICO',description:'Exposición sintética.',reference:'docs/model-validation/phase2-D-external-demography.md'},
  okunCoefficient:{name:'Sensibilidad reducida del desempleo al crecimiento',unit:'adimensional',category:'HEURISTICO',description:'No es un coeficiente de Okun estimado para España.',reference:'docs/model-validation/phase2-B-employment-inflation.md'},
  debtInterest:{name:'Coste simplificado de deuda',unit:'por año',category:'HEURISTICO',description:'No representa vencimientos ni transmisión del BCE.',reference:'docs/model-validation/phase2/C-households-fiscal.md'},
  externalDemandGrowth:{name:'Tendencia exportadora',unit:'por año',category:'HEURISTICO',description:'Escenario tendencial, no previsión.',reference:'docs/model-validation/phase2-D-external-demography.md'},
  importDemandElasticity:{name:'Elasticidad agregada de importaciones',unit:'adimensional',category:'HEURISTICO',description:'Regla central simplificada; sin precios relativos/composición.',reference:'docs/model-validation/phase2-D-external-demography.md'},
  eventMonthlyChance:{name:'Frecuencia mensual de perturbaciones sintéticas',unit:'por mes',category:'HEURISTICO',description:'Parámetro determinista del generador, no probabilidad empírica.',reference:'docs/model-validation/phase2-D-external-demography.md'},
  minInflation:{name:'Límite inferior de inflación',unit:'proporción',category:'HEURISTICO',description:'Restricción del dominio numérico.',reference:'docs/model-validation/model-equations.md'},
  maxInflation:{name:'Límite superior de inflación',unit:'proporción',category:'HEURISTICO',description:'Restricción del dominio numérico.',reference:'docs/model-validation/model-equations.md'},
  minUnemployment:{name:'Límite inferior de desempleo',unit:'proporción',category:'HEURISTICO',description:'Restricción del dominio numérico.',reference:'docs/model-validation/model-equations.md'},
  maxUnemployment:{name:'Límite superior de desempleo',unit:'proporción',category:'HEURISTICO',description:'Restricción del dominio numérico.',reference:'docs/model-validation/model-equations.md'},
};
export const PARAMETER_REGISTRY=Object.entries(M).map(([key,value])=>({key,...PARAMETER_META[key]!,value,modelVersion:MODEL_VERSION}));
export const ASSUMPTIONS = [
  ['Productividad tendencial', '0,3 % anual', 'Candidato provisional de referencia española del Banco de España; no es estimación estructural ni crecimiento potencial total. Utilización y productividad siguen simplificadas.'],
  ['Capital / producto', '3,2 años; depreciación 4 % anual', 'Heurística agregada; ninguno de los valores es un stock observado o tasa española estimada.'],
  ['Contribución de capital', '0,27', 'Heurística que transmite inversión neta a capacidad.'],
  ['Inversión privada', 'Exponente fiscal 1,25; fricción 3', 'Heurística del modelo, no elasticidad española estimada.'],
  ['Producción y capacidad', 'Ajuste 32 % mensual; techo 105 %', 'Regla heurística agregada; no usa una medida observada de utilización.'],
  ['Precios', 'Ancla 2 %; persistencia 0,97 mensual; respuesta a brecha 0,10', 'La brecha es un proxy de holgura. La respuesta es heurística y la persistencia es provisional, no una estimación española.'],
  ['Impuesto al consumo', 'Traslado central 50 %', 'Cambio fiscal mecánico trasladado una sola vez al nivel de precios; simplificación no universal.'],
  ['Empleo', 'Regla reducida de sensibilidad del desempleo al crecimiento: 0,22', 'No es un coeficiente de Okun estimado para España; se conserva por su orden de magnitud plausible.'],
  ['Hogares y fiscalidad', 'Tres grupos; cuotas y bases sintéticas', 'Heurística / construcción sintética; no representan deciles observados, IRPF observado ni cuentas SEC.'],
  ['Comercio exterior', 'Exportaciones 2 % anual; elasticidad importadora 1', 'Escenario tendencial, no previsión; elasticidad agregada simplificada. España no tiene tipo de cambio nacional; precios relativos y composición se omiten.'],
  ['Demografía', 'Regla actual del catálogo', 'Natalidad, mortalidad y residuo permanecen constantes. El residuo no es proyección observada de migración ni proyección oficial a 20 años.'],
  ['Perturbaciones sintéticas', 'Generador determinista opcional', 'Frecuencia y magnitud no son estimaciones estadísticas de acontecimientos reales.'],
  ['Cuentas públicas', 'Presupuesto fiscal sintético', 'No reproduce el saldo SEC español; cuotas e importes son heurísticos.'],
  ['Instituciones', 'Reglas de escenario', 'Generan eventos de procedimiento; no tienen efectos económicos cuantificados en este MVP.'],
  ['Incertidumbre', 'Una trayectoria por semilla', 'No son intervalos de confianza. Cambiar la semilla no sustituye la incertidumbre estructural.'],
] as const;
